default_language_version:
     python: python3
repos:
- repo: local
  hooks:
    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: python
      types: ["python"]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: ["python"]
    - id: trailing-whitespace
      name:  trailing-whitespace
      entry: trailing-whitespace-fixer
      language: python
      types: ["python"]