default_language_version:
     python: python3
repos:
- repo: local
  hooks:
    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: python
      types: ["python"]
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=88"
        - "--max-complexity=23"
        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"
      name: flake8
      entry: flake8
      language: python
      types: ["python"]
